# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XeQNgYSFYOkZa3qUzYnh58N4DW2VUGpA
"""

import math

def dupuit_equation(q, k, h1, h2, l):
  """Calculates the discharge of a steady flow in a confined aquifer using Dupuit's equation.

  Args:
    q: The discharge rate (m^3/s)
    k: The hydraulic conductivity (m/s)
    h1: The hydraulic head at point 1 (m)
    h2: The hydraulic head at point 2 (m)
    l: The distance between points 1 and 2 (m)

  Returns:
    The discharge rate (m^3/s)
  """

  return q * (h1 - h2) / l

def main():
  """Calculates the discharge of a steady flow in a confined aquifer using Dupuit's equation."""

  # Get the input parameters
  q = float(input('Enter the discharge rate (m^3/s): '))
  k = float(input('Enter the hydraulic conductivity (m/s): '))
  h1 = float(input('Enter the hydraulic head at point 1 (m): '))
  h2 = float(input('Enter the hydraulic head at point 2 (m): '))
  l = float(input('Enter the distance between points 1 and 2 (m): '))

  # Calculate the discharge rate using Dupuit's equation
  q = dupuit_equation(q, k, h1, h2, l)

  # Print the results
  print('The discharge rate is:', q, 'm^3/s')

if __name__ == '__main__':
  main()